FROM python:3.6.6-onbuild

RUN pip install --no-cache-dir -r requirements.txt

# cp -r airflow/dags/launch.py ~/airflow/dags

# airflow webserver -p 8087 --debug &

# airflow version
# airflow initdb

# python -m middlewares.to_pull

# https://hub.docker.com/_/python/